### PR TITLE
Feature/docs spellchecker

### PR DESCRIPTION
**Pull request by CrepeGoat**
This PR adds a spellchecker to the doctests routine.

I've used this to fix the existing spelling errors in the docs & docstrings (ftr: we're pretty bad at spelling "acceleration"). However, there are still 48 spelling errors being reported that I don't know exactly how best to fix due to limits of the spellchecker itself. Because of this, I've changed the spellchecker to **NOT** report spelling errors as doctest failures; instead, I encourage developers to read through the output of the spellchecker (printed in the logs of the "Docs test" GitHub Action) before pulling code into dev or main.

### CODE REVIEW

**Comment by CrepeGoat** [comment]
hmm... looks like the output in the action runner is slightly different from the output on my local machine -> need to make some more changes

**Comment by CFlaniganMide** [comment]
It looks like we could leverage some things in [pyenchant ](https://pyenchant.github.io/pyenchant/tutorial.html#chunkers)to filter out certain things if we have the right syntax around it, and it looks like some of that is already happening.

**Comment by CrepeGoat** [comment]
yeah, though beyond that I've seen a couple exceptions:

- it seems to be checking the programmatically generated .rst files, instead of the *sources* of those generated files. E.g., there are a number of failures on `plotly.graph_objs._figure.Figure`; this text isn't literally present in any of the source files, it only shows up as the output annotation for some functions in `endaq.plot`. And *normally* to fix this I'd surround those chunks in backticks to mark them as code, but I can't actually edit that text to do so because it's not a part of the source texts.

- it also seems that, in some cases, the checker isn't given enough context to determine whether a phrase is a spelling error or not. E.g., the checker registered "th" as an unknown word from the line "1/*20th* of the pulse duration". It wouldn't be terribly hard to write a rule for checking "nth" patterns, but in the above example it might have pre-parsed the "th" apart from the full word "20th" before running the checker functions, and if a program has to check "th" in isolation of what comes before it, it will not be possible to validate it correctly.

**Comment by StokesMIDE** [comment]
I like the idea (and will probably approve the PR), but is it necessary? Virtually all IDEs (and many editors) have spellcheck for text files and strings/comments in code. If devs are ignoring spellcheck in their own environments, I kind of expect them ignore it in the log of a GitHub Action as well.

**Comment by CrepeGoat** [comment]
> is it necessary? Virtually all IDEs... have spellcheck

The ~20 spelling errors (excluding formatting changes) say "yes" imo. And while some of them came from me, many of them also came from @SamRagusa and @CFlaniganMide who are both using PyCharm, so I don't think it's fair to say "IDE's fix this problem".

**Comment by StokesMIDE** [comment]
> The ~20 spelling errors (excluding formatting changes) say "yes" imo. And while some of them came from me, many of them also came from @SamRagusa and @CFlaniganMide who are both using PyCharm, so I don't think it's fair to say "IDE's fix this problem".

Fair enough. No tool will fix the problem, though, including this; it's ultimately up to the devs to heed them.

**Comment by CFlaniganMide** [comment]
> > The ~20 spelling errors (excluding formatting changes) say "yes" imo. And while some of them came from me, many of them also came from @SamRagusa and @CFlaniganMide who are both using PyCharm, so I don't think it's fair to say "IDE's fix this problem".
> 
> Fair enough. No tool will fix the problem, though, including this; it's ultimately up to the devs to heed them.

Yeah, this feels more like I need to proofread than anything else.  I'm not against having this as a step that we can reference as part of the action though; some typos will always get through and this should make it easier for other people to catch before we merge.

**Comment by CFlaniganMide** [comment]
image
All that being said, I do think that IDE spell checkers are far from perfect, and the number of false positives (this is form idelib) are pretty high.

**Comment by StokesMIDE** [comment]
We talked about this at the open source meeting; what was the decision on this? Put it in as-is, and revise later?

**Comment by CFlaniganMide** [comment]
My vote went to "just merge it in".

**Review by CFlaniganMide — APPROVED** [review]

**Review by StokesMIDE — APPROVED** [review]

**Pull request merged**
