### PR TITLE
Release/1.1.0

### PR DESCRIPTION
**Pull request by CrepeGoat**
waiting on the following PR's:
- MideTechnology/endaq-python-ide#46
- MideTechnology/endaq-python-calc#57
- #19
- #21

### CODE REVIEW

**Comment by pscheidler** [comment]
!! Remember to update the base `requirements.txt` to call out >= 1.1.0 for everything

**Comment by SamRagusa** [comment]
@CrepeGoat , is there any open PRs that need approval?   All the ones originally listed are either approved, or merged in at this point, but I know additional PRs have been created and think some of them need to be merged.   Anyone know of a currently open PR intended for this 1.1.0 release which needs approval?    I'll get right on that if so

**Comment by CrepeGoat** [comment]
@SamRagusa nope I think we're all set! just need the final review now.

I'll also send a docs render link, once RTD decides to render it... :\

**Comment by CrepeGoat** [comment]
Finally! RTD test link: https://docs.endaq.com/en/release-1.1.0/

**Pull request merged**
