### PR TITLE
Improved `get_doc()` error message if opening a nonexistent file.

### PR DESCRIPTION
**Pull request by StokesMIDE**
See issue #81.

Also added `headers` kwarg (primarily for future use w/ cloud)

### CODE REVIEW

**Comment by StokesMIDE** [comment]
Fixed/worked around issue with `file://` URLs under *NIX. I'm still not sure why the filenames got weird, though.

**Comment by CFlaniganMide** [comment]
> Fixed/worked around issue with `file://` URLs under *NIX. I'm still not sure why the filenames got weird, though.

Was this getting caught by tests?

**Comment by StokesMIDE** [comment]
> Was this getting caught by tests?

Yes, YA variant of the 'works on my machine' scenario... all the Linux and Mac OS tests were failing, but the tests were passing under Windows.

**Review by CFlaniganMide — APPROVED** [review]
Looks good to me

**Pull request merged**
