### PR TITLE
Fix/quicker tests

### PR DESCRIPTION
**Pull request by CrepeGoat**
So profiling... I should do that more 😅

### CODE REVIEW

**Review by CFlaniganMide — APPROVED** [review]
I definitely like faster tests, but what does adding the raw keyword do?

**Comment by CrepeGoat** [comment]
> what does adding the raw keyword do?

From [the pandas docs](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.apply.html):

> Determines if row or column is passed as a Series or ndarray object:
> - `False`: passes each row or column as a Series to the function.
> - `True`: the passed function will receive ndarray objects instead. If you are just applying a NumPy reduction function this will achieve much better performance.

**Comment by CFlaniganMide** [comment]
> From [the pandas docs](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.apply.html):
> 
> > Determines if row or column is passed as a Series or ndarray object:
> > 
> > * `False`: passes each row or column as a Series to the function.
> > * `True`: the passed function will receive ndarray objects instead. If you are just applying a NumPy reduction function this will achieve much better performance.

Ok, that makes sense.  Glad it's running so much quicker.

**Review by StokesMIDE — APPROVED** [review]
Looks good.

Overall, it could probably use some comments/docstrings, to help others diagnose the cause of a failed test. Most of our other tests would probably benefit from some comments as well, so this isn't an explicit request for changes.

**Pull request merged**
