### PR TITLE
refactored markdown text to fix formatting issues in webinar notebooks

### PR DESCRIPTION
**Pull request by CrepeGoat**
small formatting fixes for webinar notebooks. This is hard to see from the file diffs, but this includes:

- adding more space above lists so the list text isn't simply treated as a wrapped paragraph
- adding more indentation to nested lists s.t. the nesting is rendered correctly
- changing some LaTeX to render equations more cleanly

### CODE REVIEW

**Review by CFlaniganMide — CHANGES_REQUESTED** [review]
This looks pretty good, but there's something preventing the python code blocks from doing syntax formatting.

**Comment by CrepeGoat** [comment]
> This looks pretty good, but there's something preventing the python code blocks from doing syntax formatting.

weird. can you give an example that I can look into more?

**Comment by CFlaniganMide** [comment]
> weird. can you give an example that I can look into more?

https://docs.endaq.com/en/feature-refactor-ipynbs/webinars/Webinar_Introduction_NumPy_and_Pandas.html#Manually-or-from-Lists

The build [here](https://readthedocs.com/projects/mide-technology-endaq-python/builds/865565/) has a lot of errors that follow the format `
/home/docs/checkouts/readthedocs.org/user_builds/mide-technology-endaq-python/checkouts/feature-refactor-ipynbs/docs/webinars/Webinar_Introduction_NumPy_and_Pandas.ipynb:: WARNING: Pygments lexer name 'ipython3' is not known`

**Comment by CrepeGoat** [comment]
interesting... imo our tests should catch this before we do, but it looks like they're happily passing with these errors being emitted. I'll add an issue for the tests, and keep working at removing them from this branch (I think I'm now reproducing them locally). Thanks Connor 👍

**Comment by CrepeGoat** [comment]
Okay, I think I figured it out. Looks like in order to parse the code cells correctly in the docs, `nbsphinx` needs `ipython` installed as indicated in [the old nbsphinx docs](https://nbsphinx.readthedocs.io/en/0.2.12/usage.html#Syntax-Highlighting) (but not the new docs 🤷‍♂️ ). So I added that in 7fa4cd3dfe399d654611a02b9664a891d0ecc4f0.

On another note, it looks like the pdf building routine was also adding thousands of lines to the logs, mostly due to unicode issues? (e.g., [this build](https://readthedocs.com/projects/mide-technology-endaq-python/builds/865887/).) So just to keep that leaner I also removed the PDF creation routine in 96e0b2fb4f9d3c0edaa1350492b27e07e05f56cc.

But with those two changes it should be good! there are still 4 warnings, but they're now far fewer than there used to be, and I'm not exactly sure how best to avoid them atm.

**Comment by CrepeGoat** [comment]
And as a side-note: this repo has configured readthedocs builds to install dependencies based on the concrete dependencies listed in `./docs/requirements.txt`. Right now that file specifies `Sphinx==4.2.0`, but the current version of sphinx is `4.4.0`. So at some point the file could stand to get updated with more recent versions of the required dependencies, but I think that's more appropriate to do in another PR.

**Review by CFlaniganMide — APPROVED** [review]
Worth looking into the newer versions of stuff later, but for now this is working how we want it.

**Pull request merged**
