### PR TITLE
Update psd.py to fix vc curve bug

### PR DESCRIPTION
**Pull request by shanlyMIDE**
See https://github.com/MideTechnology/endaq-python/issues/51

### CODE REVIEW

**Comment by shanlyMIDE** [comment]
Hopefully I did it correctly!? @CrepeGoat @pscheidler 

Danger danger if I did... we may see more of these

**Comment by CrepeGoat** [comment]
yeah this one is still pretty frustrating, because I have a test to check that the two methods are the same and atm the tests are passing =_= I want to think about this one for a bit, but if we need the fix we can merge it in for now

**Review by CrepeGoat — APPROVED** [review]
definitely an improvement! but I'll want to do a proper fix later on so that passing `agg=np.sum` works as expected.

**Comment by pscheidler** [comment]
closes #51

**Pull request merged**
