### PR TITLE
Feature/92 module readmes

### PR DESCRIPTION
**Pull request by StokesMIDE**
This moves the README contents from submodules to the documentation. This is similar to #107 (which should be merged first), but with less editing of the content.

See issue #92

### CODE REVIEW

**Comment by CrepeGoat** [comment]
docs rendered here: https://docs.endaq.com/en/feature-92_module_readmes/

**Review by shanlyMIDE — APPROVED** [review]
looks good!

**Review by CFlaniganMide — APPROVED** [review]
This looks good

**Review by CrepeGoat — APPROVED** [review]
not my style per-se, but otherwise looks good

**Pull request merged**
