### PR TITLE
changed resampled time

### PR DESCRIPTION
**Pull request by shanlyMIDE**
By passing in `df.index.values.astype('datetime64[s]')` instead of just `df.index` messes up the resampled index to all be the same value.

Here's a [colab you can try out in a test](https://colab.research.google.com/drive/1YBDmWztWlr-iT2-3YxgiZhXbmaOHTaSV#scrollTo=oOR-yKB8LLF1).
image

### CODE REVIEW

**Comment by shanlyMIDE** [comment]
@SamRagusa  and @CFlaniganMide  I still think this PR as is should be okay. It works correctly on our three index types: https://colab.research.google.com/drive/1hjMWXPlO2pxRRU1hSMLXTGYSgi9WCt9l?usp=sharing

In the images below are the results with my fix: 
image

image

We get an error when trying to use `timedelta` with code as is:
image

**Comment by SamRagusa** [comment]
The tests are failing on your new implementation because of the same Scipy bug that originally caused me an issue, which [I currently have an open issue in the Scipy repo about.](https://github.com/scipy/scipy/issues/15153).  If you look at the logs of the failing tests, the unique time differences between time deltas is messed up in the same way as detailed in that issue.

Am I correct in saying that if we could get the current implementation to keep correct date/time precision (in comparison to now where it appears to just be keeping the date), then it'd be working as desired?

**Comment by shanlyMIDE** [comment]
I'll define the `current` implementation as what is in the development branch now and then the `proposed` implementation is what's in my new branch. There are two issues with the `current` implementation 

- the precision is lost
- it always returns an index of type `'datetime64[s]'` regardless of what it actually is (simple floats, time deltas, etc.)

**Comment by shanlyMIDE** [comment]
Nice, looks good! Can we merge it in?

**Review by StokesMIDE — APPROVED** [review]

**Comment by shanlyMIDE** [comment]
Closes #158

**Pull request merged**
