### PR TITLE
Feature/plot docs

### PR DESCRIPTION
**Pull request by CFlaniganMide**
Making this PR to solicit feedback.  I've added an extension to allow us to add plots to the documentation.  I'm going to swap it out for one that supports plotly, so we should be able to use our plotting library.

https://docs.endaq.com/en/feature-plot_docs/endaq/calc_usage.html

### CODE REVIEW

**Review by shanlyMIDE — COMMENTED** [review]
I LOVE THIS!!!!!!!!!!!!

Awesome find @CFlaniganMide !

**Comment by shanlyMIDE** [comment]
Wait @CFlaniganMide I am a little silly possibly with the theme stuff, but would it make sense to add this line after importing endaq to make the plots use our custom theme?

```
endaq.plot.utilities.set_theme('endaq_light')
```

**Review by shanlyMIDE — COMMENTED** [review]
Looks good, so exciting!

**Comment by CFlaniganMide** [comment]
I'd like to freeze the scope of this PR here so we can get it merged in.

**Review by shanlyMIDE — APPROVED** [review]
I hear you @CFlaniganMide, I'll stop adding to it. Rest of team, let's approve this!

**Comment by SamRagusa** [comment]
The first two of the examples in the code doc don't have code comments which really should exist on a document like this

**Review by StokesMIDE — APPROVED** [review]

**Pull request merged**
