### PR TITLE
added `endaq.plot.utilities` to docs

### PR DESCRIPTION
**Pull request by CrepeGoat**
rendered docs at https://docs.endaq.com/en/fix-endaq-plot-docs/

### CODE REVIEW

**Comment by SamRagusa** [comment]
It appears that variables/functions that are imported are being put into the docs.  

For example the `make_subplots` function in that doc isn't mine, it's Plotly's function that I imported (that huge docstring is also Plotly's).  Another example is the `get_center_of_coordinates` which appears twice in the docs, once for it's actual declaration and another time for when it was imported into another file.

**Comment by CrepeGoat** [comment]
> It appears that variables/functions that are imported are being put into the docs.

well fixing that would require changes to `plot`, which we won't see in the docs here unless we make another `plot` release to go along with this...

**Review by SamRagusa — APPROVED** [review]
Looks good to me

**Review by SamRagusa — APPROVED** [review]
I'm not entirely sure what the goal of the change to conf.py was, but everything else looks good

**Comment by CrepeGoat** [comment]
no worries; I just removed an unused sphinx extension and added the `todo` extension, which adds support for doing stuff like `.. todo:: SOME TODO COMMENT` in the docstrings, which I've been seeing a lot of in other people's work

**Pull request merged**
