### PR TITLE
allow getting channel with minimum samples

### PR DESCRIPTION
**Pull request by shanlyMIDE**
in using this function I've found that sometimes I actually want to get the smaller channel, should be pretty small but helpful change!

### CODE REVIEW

**Comment by shanlyMIDE** [comment]
I use this notebook to test this branch (and the original one) but I would be at a loss as to how to actually develop tests inside our repo, I'd have to leave that to our big guns!

https://colab.research.google.com/drive/1NCte1dvwSaGxKZYN9JtNouA3mitwR61k

**Comment by StokesMIDE** [comment]
Thinking about it, the parameter name `descending` seems a little confusing; it isn't clear what is being descended. From the user's perspective, the data isn't being sorted, they're just getting either the most or least item. Maybe call it 'least', default `False`. 

For that matter, the name `sort_by` has the same issue; it implies the function returns sorted set of sensor data, and the sorting is really just internal plumbing. A better name might be `criteria`. Or possibly `key`, as is used in some standard Python functions, although the values in those cases are functions.

**Comment by shanlyMIDE** [comment]
yeah I agree with you and defer to you on parameter naming! I didn't feel too good about the ones I selected anyways...

**Comment by StokesMIDE** [comment]
I chose `criteria` and `least` as the parameter names. Functions with a `key` parameter work in a consistent way, which is different.

**Pull request merged**
