### PR TITLE
Init batch

### PR DESCRIPTION
**Pull request by CrepeGoat**
The plan was to merge in the batch changes from a fork of this repo (see [MideTechnology/endaq-python-batch-dev](https://github.com/MideTechnology/endaq-python-batch-dev)). However, the changes fit pretty nicely into a single branch, and @shanlyMIDE reiterated that the only prereq's for merging in batch was:
1. to have the existing functionality from the original project work as a part of this repo,
2. to refactor the library to use `endaq.calc` for calculations (see e789e76346690ca9823af3ffb70490d151081e1c), and
3. to use `endaq.ide.get_doc` to open files (see e789e76346690ca9823af3ffb70490d151081e1c),

all of which have been done in this branch.

So... can I just merge this?

### CODE REVIEW

**Review by shanlyMIDE — APPROVED** [review]
Looks good, I can’t wait to try it out!

**Comment by CrepeGoat** [comment]
tests still failing -> reverting to draft

**Comment by StokesMIDE** [comment]
> tests still failing -> reverting to draft

I think it can probably remain a 'real' PR; the fails look like they're sporadic. The unusual one (ubuntu-latest, 3.7, push) was a problem fetching a file from a URL, which could have been a network glitch; the other (macos-latest, 3.8, push) looks like the same thing that's been randomly happening elsewhere.

**Comment by CrepeGoat** [comment]
> Should we mark tests that have dependencies outside of the library itself (e.g., fetching URLs) as being allowed to fail?

I... don't know exactly how we'd do that off the top of my head. I wouldn't hate it, and in the meantime we can always re-run tests.

**Comment by CFlaniganMide** [comment]
> > Should we mark tests that have dependencies outside of the library itself (e.g., fetching URLs) as being allowed to fail?
> 
> I... don't know exactly how we'd do that off the top of my head. I wouldn't hate it, and in the meantime we can always re-run tests.

I think it might be worth looking at later.  Marking an action as cancelled instead of failing if a dependency has an issue might work.  I think that inspecting failures and re-running when the code is not the issue isn't a problem.

**Comment by CrepeGoat** [comment]
> I think it can probably remain a 'real' PR; the fails look like they're sporadic. The unusual one (ubuntu-latest, 3.7, push) was a problem fetching a file from a URL, which could have been a network glitch

👍 -> marking ready for review

**Review by StokesMIDE — APPROVED** [review]

**Pull request merged**
