### PR TITLE
Feature/batch/refactor ide utils

### PR DESCRIPTION
**Pull request by CrepeGoat**
This PR refactors some of the internal (sub)channel-selection code. The changes have no functional impact, but remove an unnecessary layer of abstraction in assigning aliases to measures (e.g., "Acceleration" -> "acc").

### CODE REVIEW

**Comment by StokesMIDE** [comment]
Since all the sub-packages have been joined, the measurement type stuff in `endaq.ide.measurement` is available. It might be better to use that, just so the measurement type key strings are all compatible.

**Comment by CrepeGoat** [comment]
> It might be better to use that, just so the measurement type key strings are all compatible.

I considered it. However using those would mean the unit types, which I get straight from the `Dataset` document via the subchannels, are still being mapped to some other set of labels. That itself is an abstraction away from "the single source of truth" (i.e., the labels provided in the `Dataset`), and the goal of this PR is to *remove* the abstraction. That was my reasoning for not using the labels in `endaq.ide.measurement`.

Speaking of, would we ever want to move the `endaq.ide.measurement` labels into idelib? For example, replace all the uses of units strings like `"Acceleration"` with their corresponding `MeasureType` instance?

**Comment by StokesMIDE** [comment]
> > It might be better to use that, just so the measurement type key strings are all compatible.
> 
> I considered it. However using those would mean the unit types, which I get straight from the `Dataset` document via the subchannels, are still being mapped to some other set of labels. That itself is an abstraction away from "the single source of truth" (i.e., the labels provided in the `Dataset`), and the goal of this PR is to _remove_ the abstraction. That was my reasoning for not using the labels in `endaq.ide.measurement`.

One advantage of using things in `endaq.ide.measurement` is it does pattern matches on the channel/subchannel labels to make the types more generic; it is less dependent on specific string matching. Its system for getting channels/subchannels by type is pretty robust. The scope of such a refactoring may be beyond what is intended in this PR, though, and if so, it should be considered in the future.

> Speaking of, would we ever want to move the `endaq.ide.measurement` labels into idelib? For example, replace all the uses of units strings like `"Acceleration"` with their corresponding `MeasureType` instance?

I do think the measurement stuff belongs in `idelib`; I need it for my device library stuff (which uses `idelib`) as well, so it's been something I've been thinking about. `endaq.ide.measurement` attaches MeasurementType information to Channels/SubChannels. I don't think we should replace strings, though; the labels can be important.

**Comment by CrepeGoat** [comment]
> The scope of such a refactoring may be beyond what is intended in this PR, though

I'd say that's true, this PR isn't very ambitious; the only goal of it is to remove the relabeled strings (e.g., "acc"). But once I get some more research in on your work, I may want to refactor this again to use the `MeasurementType` stuff.

> ... [`endaq.ide.measurement`] does pattern matches on the channel/subchannel labels to make the types more generic

I don't know what you mean here; do you mean pattern matching on the `channel.name` attribute (e.g., `"<SubChannel 8.0 '100g PE Acceleration:X (100g)': Acceleration (g)>"`)? Can you point me to the code for this pattern matching?

**Comment by StokesMIDE** [comment]
> I don't know what you mean here; do you mean pattern matching on the `subchannel.name` attribute (e.g., `"<SubChannel 8.0 '100g PE Acceleration:X (100g)': Acceleration (g)>"`)? Can you point me to the code for this pattern matching?

In `endaq.ide.measurement`, matching is done against subchannel labels via substrings or strings with glob-style wildcards; I felt the label was more reliable than the channel/subchannel name. The matching is done in [`MeasurementType.match()`](https://github.com/MideTechnology/endaq-python/blob/main/endaq/ide/measurement.py#L164).

In any case, this is beyond the scope of this PR and probably shouldn't hold things up.

**Review by StokesMIDE — APPROVED** [review]

**Pull request merged**
